<a href="https://colab.research.google.com/github/JahnaviRudresh/Cognifyz_Machine_Learning-_Internship/blob/main/Cognifyz_task_02_Restaurant_Recommendation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!


In [ ]:
import os

print("CSV files in Colab:")
for file in os.listdir('/content'):
    if file.endswith('.csv'):
        print(file)

CSV files in Colab:
Dataset  (1).csv


In [ ]:
df = pd.read_csv('/content/Dataset  (1).csv')

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (9551, 21)


In [ ]:
print(df.columns.tolist())

['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address', 'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating', 'Rating color', 'Rating text', 'Votes']


In [ ]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64


In [ ]:
df['Cuisines'] = df['Cuisines'].fillna('Unknown')

print("Missing Cuisines after cleaning:",
      df['Cuisines'].isnull().sum())

Missing Cuisines after cleaning: 0


In [ ]:
recommendation_data = df[
    ['Restaurant ID', 'Restaurant Name', 'Cuisines', 'Price range']
].copy()

recommendation_data.head()

,Restaurant ID,Restaurant Name,Cuisines,Price range
0,6317637,Le Petit Souffle,"French, Japanese, Desserts",3
1,6304287,Izakaya Kikufuji,Japanese,3
2,6300002,Heat - Edsa Shangri-La,"Seafood, Asian, Filipino, Indian",4
3,6318506,Ooma,"Japanese, Sushi",4
4,6314302,Sambo Kojin,"Japanese, Korean",4


In [ ]:
user_cuisine = "North Indian"
user_price_range = 2

print("Preferred cuisine:", user_cuisine)
print("Preferred price range:", user_price_range)

Preferred cuisine: North Indian
Preferred price range: 2


In [ ]:
recommended = recommendation_data[
    (recommendation_data['Cuisines'].str.contains(
        user_cuisine, case=False, na=False
    )) &
    (recommendation_data['Price range'] == user_price_range)
]

print("Number of matching restaurants:", len(recommended))

recommended.head(10)

Number of matching restaurants: 1537


,Restaurant ID,Restaurant Name,Cuisines,Price range
625,3400341,Rangrezz Restaurant,"North Indian, Mughlai",2
626,3400005,Time2Eat - Mama Chicken,North Indian,2
643,3400392,Thaaliwala,"North Indian, Fast Food",2
656,110237,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
683,2400009,Sagar Ratna,"South Indian, North Indian, Chinese, Continental",2
685,2200011,Makhan Fish and Chicken Corner,"North Indian, Chinese",2
694,2200283,Sakhis Watz Kukin,"North Indian, Chinese",2
696,2200149,Shudh Restaurant,"North Indian, South Indian, Chinese, Fast Food",2
697,2200043,Bade Bhai Ka Brothers' Dhaba,"North Indian, Fast Food",2
698,2200044,Bharawan Da Dhaba,"North Indian, Fast Food",2


In [ ]:
recommended[['Restaurant Name', 'Cuisines', 'Price range']].head(10)

,Restaurant Name,Cuisines,Price range
625,Rangrezz Restaurant,"North Indian, Mughlai",2
626,Time2Eat - Mama Chicken,North Indian,2
643,Thaaliwala,"North Indian, Fast Food",2
656,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
683,Sagar Ratna,"South Indian, North Indian, Chinese, Continental",2
685,Makhan Fish and Chicken Corner,"North Indian, Chinese",2
694,Sakhis Watz Kukin,"North Indian, Chinese",2
696,Shudh Restaurant,"North Indian, South Indian, Chinese, Fast Food",2
697,Bade Bhai Ka Brothers' Dhaba,"North Indian, Fast Food",2
698,Bharawan Da Dhaba,"North Indian, Fast Food",2


In [ ]:
cuisine_text = recommendation_data['Cuisines'].fillna('Unknown')

print(cuisine_text.head())

0          French, Japanese, Desserts
1                            Japanese
2    Seafood, Asian, Filipino, Indian
3                     Japanese, Sushi
4                    Japanese, Korean
Name: Cuisines, dtype: object


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

cuisine_matrix = vectorizer.fit_transform(cuisine_text)

print("Cuisine matrix shape:", cuisine_matrix.shape)

Cuisine matrix shape: (9551, 151)


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(cuisine_matrix)

print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (9551, 9551)


In [ ]:
restaurant_index = 0

similar_scores = similarity_matrix[restaurant_index]

print("Selected restaurant:")
print(recommendation_data.iloc[restaurant_index]['Restaurant Name'])

print("\nTop similar restaurant indexes:")
print(similar_scores.argsort()[-6:][::-1])

Selected restaurant:
Le Petit Souffle

Top similar restaurant indexes:
[   0 4993   70  461  460 9484]


In [ ]:
similar_indexes = similar_scores.argsort()[-6:][::-1]

similar_indexes = [i for i in similar_indexes if i != restaurant_index]

recommendations = recommendation_data.iloc[similar_indexes]

recommendations[['Restaurant Name', 'Cuisines', 'Price range']]

,Restaurant Name,Cuisines,Price range
4993,Tokyo Mon Amour,"Japanese, French",4
70,Paris 6 Classique,French,4
461,Rhubarb Le Restaurant,French,4
460,Jaan,French,4
9484,Restaurant Mosaic @ The Orient,French,4


In [ ]:
print("Available price ranges:")
print(sorted(recommendation_data['Price range'].unique()))

Available price ranges:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]


In [ ]:
print("User preferred cuisine:", user_cuisine)
print("User preferred price range:", user_price_range)

User preferred cuisine: North Indian
User preferred price range: 2


In [ ]:
price_matched = recommendation_data[
    recommendation_data['Price range'] == user_price_range
].copy()

print("Restaurants matching the preferred price range:",
      len(price_matched))

Restaurants matching the preferred price range: 3113


In [ ]:
price_matches = recommendation_data[
    recommendation_data['Price range'] == user_price_range
].copy()

print("Restaurants matching the preferred price range:", len(price_matches))

Restaurants matching the preferred price range: 3113


In [ ]:
price_match_indexes = price_matches.index

print("Number of matching indexes:", len(price_match_indexes))

Number of matching indexes: 3113


In [ ]:
price_similarity_scores = similarity_matrix[restaurant_index, price_match_indexes]

print("Number of similarity scores:", len(price_similarity_scores))

Number of similarity scores: 3113


In [ ]:
top_positions = price_similarity_scores.argsort()[::-1][:10]

print("Top 10 similarity positions:")
print(top_positions)

Top 10 similarity positions:
[   1 3012 2108   48 1945 2613 2372 3013 1266 1673]


In [ ]:
top_restaurant_indexes = price_match_indexes[top_positions]

print("Top restaurant indexes:")
print(top_restaurant_indexes)

Top restaurant indexes:
Index([22, 9141, 6400, 187, 5925, 8076, 7082, 9142, 3571, 4877], dtype='int64')


In [ ]:
final_recommendations = recommendation_data.loc[
    top_restaurant_indexes,
    ['Restaurant Name', 'Cuisines', 'Price range']
]

final_recommendations

,Restaurant Name,Cuisines,Price range
22,Chez Michou,"Fast Food, French",2
9141,Baker Street,"Bakery, French",2
6400,Dimsum Vs Sushi,"Japanese, Chinese",2
187,Sakura Sushi & Grill,"Asian, Japanese",2
5925,Yo Wok,"Chinese, Japanese, Thai",2
8076,The Bento Cafe,"Asian, Chinese, Japanese",2
7082,Drool Waffles,Desserts,2
9142,Zuka Choco-la,Desserts,2
3571,Drool Waffles,Desserts,2
4877,Moon of Taj,Desserts,2


In [ ]:
cuisine_matches = recommendation_data[
    recommendation_data['Cuisines'].str.contains(
        user_cuisine, case=False, na=False
    )
].copy()

print("Restaurants matching the preferred cuisine:", len(cuisine_matches))

Restaurants matching the preferred cuisine: 3960


In [ ]:
final_matches = cuisine_matches[
    cuisine_matches['Price range'] == user_price_range
].copy()

print("Restaurants matching cuisine and price range:", len(final_matches))

Restaurants matching cuisine and price range: 1537


In [ ]:
final_matches[
    ['Restaurant Name', 'Cuisines', 'Price range']
].head(10)

,Restaurant Name,Cuisines,Price range
625,Rangrezz Restaurant,"North Indian, Mughlai",2
626,Time2Eat - Mama Chicken,North Indian,2
643,Thaaliwala,"North Indian, Fast Food",2
656,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
683,Sagar Ratna,"South Indian, North Indian, Chinese, Continental",2
685,Makhan Fish and Chicken Corner,"North Indian, Chinese",2
694,Sakhis Watz Kukin,"North Indian, Chinese",2
696,Shudh Restaurant,"North Indian, South Indian, Chinese, Fast Food",2
697,Bade Bhai Ka Brothers' Dhaba,"North Indian, Fast Food",2
698,Bharawan Da Dhaba,"North Indian, Fast Food",2


In [ ]:
match_indexes = final_matches.index

match_similarity = similarity_matrix[
    restaurant_index, match_indexes
]

top_matches = match_similarity.argsort()[::-1][:10]

print("Top 10 matching positions:")
print(top_matches)

Top 10 matching positions:
[ 946  204    3 1201  446  447 1277 1495  507  412]


In [ ]:
top_match_indexes = match_indexes[top_matches]

print("Top restaurant indexes:")
print(top_match_indexes)

Top restaurant indexes:
Index([6008, 1723, 656, 7426, 3129, 3137, 8043, 9042, 3446, 2875], dtype='int64')


In [ ]:
final_recommendations = recommendation_data.loc[
    top_match_indexes,
    ['Restaurant Name', 'Cuisines', 'Price range']
]

final_recommendations

,Restaurant Name,Cuisines,Price range
6008,Club India Cafe & Restaurant,"North Indian, Fast Food, Chinese, Japanese, As...",2
1723,Baxman Delivers,"North Indian, Chinese, Fast Food, Desserts",2
656,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
7426,Nathu's Sweets,"North Indian, South Indian, Chinese, Street Fo...",2
3129,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
3137,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
8043,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
9042,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
3446,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
2875,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2


In [ ]:
final_recommendations = final_recommendations.drop_duplicates(
    subset='Restaurant Name'
)

final_recommendations

,Restaurant Name,Cuisines,Price range
6008,Club India Cafe & Restaurant,"North Indian, Fast Food, Chinese, Japanese, As...",2
1723,Baxman Delivers,"North Indian, Chinese, Fast Food, Desserts",2
656,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
7426,Nathu's Sweets,"North Indian, South Indian, Chinese, Street Fo...",2
3129,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2


In [ ]:
final_recommendations = final_recommendations.drop_duplicates(
    subset='Restaurant Name'
)

final_recommendations

,Restaurant Name,Cuisines,Price range
6008,Club India Cafe & Restaurant,"North Indian, Fast Food, Chinese, Japanese, As...",2
1723,Baxman Delivers,"North Indian, Chinese, Fast Food, Desserts",2
656,Kabir Restaurant,"North Indian, Chinese, Continental, Desserts, ...",2
7426,Nathu's Sweets,"North Indian, South Indian, Chinese, Street Fo...",2
3129,Haldiram's,"North Indian, South Indian, Chinese, Street Fo...",2
